name: Check Rules Update

on:
  # on push for test
  push:
    branches: master

  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC+8 = 20
    - cron:  '0 12 * * *'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r check_rules_update/requirements.txt
    - name: Check rules update
      run: |
        python check_rules_update/check_rules_update.py
